services:
  - type: web
    name: ai-resume-generator-backend-subash
    runtime: node
    plan: free
    rootDir: ./backend
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://ai-resume-generator-subash.vercel.app
    healthCheckPath: /health
    autoDeploy: true 